#!/bin/bash

# Install pre-commit if not already installed
if ! command -v pre-commit &> /dev/null
then
    # Install pre-commit using the appropriate package manager
    if command -v pip &> /dev/null
    then
        pip install pre-commit
    elif command -v brew &> /dev/null
    then
        brew install pre-commit
    else
        echo "Unable to install pre-commit. Please install it manually."
    fi
fi

# Install hooks if pre-commit is installed
if command -v pre-commit &> /dev/null
then
    # Install hooks from .pre-commit-config.yaml
    pre-commit install
fi
